blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/lukejmorrison/yt-dlp-wizwam/security/advisories
    about: Please do not report security vulnerabilities publicly. Follow the guidance in SECURITY.md.
